name: page-build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: szenius/set-timezone@v1.1
      with:
        timezoneLinux: "Asia/Shanghai"

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: npm install and build
      run: |
        npm install
        npm run build

    - name: Deploy to GitHub page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: "public/"
        force_orphan: true

    - name: copy file to server SZX-CC
      uses: burnett01/rsync-deployments@5.0
      with:
        switches: -avzr --delete
        path: "dist/"
        remote_path: ${{ secrets.HTML_PATH }}
        remote_host: ${{ secrets.HOST_SZXCC }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}
